
package com.roomreservation.service;

import com.roomreservation.RoomReservation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoomReservationImplService", targetNamespace = "http://roomreservation.com/", wsdlLocation = "file:/home/nicolas/Documents/soen423_a3/src/com/roomreservation/roomreservation.wsdl")
public class RoomReservationImplService
    extends Service
{

    private final static URL ROOMRESERVATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROOMRESERVATIONIMPLSERVICE_EXCEPTION;
    private final static QName ROOMRESERVATIONIMPLSERVICE_QNAME = new QName("http://roomreservation.com/", "RoomReservationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/nicolas/Documents/soen423_a3/src/com/roomreservation/roomreservation.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROOMRESERVATIONIMPLSERVICE_WSDL_LOCATION = url;
        ROOMRESERVATIONIMPLSERVICE_EXCEPTION = e;
    }

    public RoomReservationImplService() {
        super(__getWsdlLocation(), ROOMRESERVATIONIMPLSERVICE_QNAME);
    }

    public RoomReservationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROOMRESERVATIONIMPLSERVICE_QNAME, features);
    }

    public RoomReservationImplService(URL wsdlLocation) {
        super(wsdlLocation, ROOMRESERVATIONIMPLSERVICE_QNAME);
    }

    public RoomReservationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROOMRESERVATIONIMPLSERVICE_QNAME, features);
    }

    public RoomReservationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomReservationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoomReservation
     */
    @WebEndpoint(name = "RoomReservationImplPort")
    public com.roomreservation.RoomReservation getRoomReservationImplPort() {
        return super.getPort(new QName("http://roomreservation.com/", "RoomReservationImplPort"), com.roomreservation.RoomReservation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoomReservation
     */
    @WebEndpoint(name = "RoomReservationImplPort")
    public com.roomreservation.RoomReservation getRoomReservationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://roomreservation.com/", "RoomReservationImplPort"), RoomReservation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROOMRESERVATIONIMPLSERVICE_EXCEPTION!= null) {
            throw ROOMRESERVATIONIMPLSERVICE_EXCEPTION;
        }
        return ROOMRESERVATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
