// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: centralRepository.proto

package com.roomreservation.protobuf.protos;

public interface CentralRepositoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.roomreservation.collection.CentralRepository)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string action = 1;</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>optional string action = 1;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>optional string action = 1;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>optional string host = 3;</code>
   * @return Whether the host field is set.
   */
  boolean hasHost();
  /**
   * <code>optional string host = 3;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <code>optional string host = 3;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>optional int32 port = 4;</code>
   * @return Whether the port field is set.
   */
  boolean hasPort();
  /**
   * <code>optional int32 port = 4;</code>
   * @return The port.
   */
  int getPort();

  /**
   * <code>optional string path = 5;</code>
   * @return Whether the path field is set.
   */
  boolean hasPath();
  /**
   * <code>optional string path = 5;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 5;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional string campus = 6;</code>
   * @return Whether the campus field is set.
   */
  boolean hasCampus();
  /**
   * <code>optional string campus = 6;</code>
   * @return The campus.
   */
  java.lang.String getCampus();
  /**
   * <code>optional string campus = 6;</code>
   * @return The bytes for campus.
   */
  com.google.protobuf.ByteString
      getCampusBytes();

  /**
   * <code>optional string type = 7;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional string type = 7;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 7;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional bool status = 8;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>optional bool status = 8;</code>
   * @return The status.
   */
  boolean getStatus();
}
