// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: centralRepository.proto

package com.roomreservation.protobuf.protos;

public final class CentralRepositoryProtos {
  private CentralRepositoryProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_roomreservation_collection_CentralRepository_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_roomreservation_collection_CentralRepository_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027centralRepository.proto\022\036com.roomreser" +
      "vation.collection\"{\n\021CentralRepository\022\016" +
      "\n\006action\030\001 \001(\t\022\014\n\004host\030\003 \001(\t\022\014\n\004port\030\004 \001" +
      "(\005\022\014\n\004path\030\005 \001(\t\022\016\n\006campus\030\006 \001(\t\022\014\n\004type" +
      "\030\007 \001(\t\022\016\n\006status\030\010 \001(\010B@\n#com.roomreserv" +
      "ation.protobuf.protosB\027CentralRepository" +
      "ProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_roomreservation_collection_CentralRepository_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_roomreservation_collection_CentralRepository_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_roomreservation_collection_CentralRepository_descriptor,
        new java.lang.String[] { "Action", "Host", "Port", "Path", "Campus", "Type", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
