// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listOfTimeSlots.proto

package com.roomreservation.protobuf.protos;

public interface ListOfTimeSlotsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.roomreservation.collection.ListOfTimeSlots)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string timeslot = 1;</code>
   * @return A list containing the timeslot.
   */
  java.util.List<java.lang.String>
      getTimeslotList();
  /**
   * <code>repeated string timeslot = 1;</code>
   * @return The count of timeslot.
   */
  int getTimeslotCount();
  /**
   * <code>repeated string timeslot = 1;</code>
   * @param index The index of the element to return.
   * @return The timeslot at the given index.
   */
  java.lang.String getTimeslot(int index);
  /**
   * <code>repeated string timeslot = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the timeslot at the given index.
   */
  com.google.protobuf.ByteString
      getTimeslotBytes(int index);
}
