// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listOfTimeSlots.proto

package com.roomreservation.protobuf.protos;

public final class ListOfTimeSlotsProtos {
  private ListOfTimeSlotsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_roomreservation_collection_ListOfTimeSlots_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_roomreservation_collection_ListOfTimeSlots_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025listOfTimeSlots.proto\022\036com.roomreserva" +
      "tion.collection\"#\n\017ListOfTimeSlots\022\020\n\010ti" +
      "meslot\030\001 \003(\tB>\n#com.roomreservation.prot" +
      "obuf.protosB\025ListOfTimeSlotsProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_roomreservation_collection_ListOfTimeSlots_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_roomreservation_collection_ListOfTimeSlots_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_roomreservation_collection_ListOfTimeSlots_descriptor,
        new java.lang.String[] { "Timeslot", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
