// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: listOfTimeSlots.proto

package com.roomreservation.protobuf.protos;

/**
 * Protobuf type {@code com.roomreservation.collection.ListOfTimeSlots}
 */
public final class ListOfTimeSlots extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.roomreservation.collection.ListOfTimeSlots)
    ListOfTimeSlotsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListOfTimeSlots.newBuilder() to construct.
  private ListOfTimeSlots(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListOfTimeSlots() {
    timeslot_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListOfTimeSlots();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListOfTimeSlots(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              timeslot_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            timeslot_.add(bs);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        timeslot_ = timeslot_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.roomreservation.protobuf.protos.ListOfTimeSlotsProtos.internal_static_com_roomreservation_collection_ListOfTimeSlots_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.roomreservation.protobuf.protos.ListOfTimeSlotsProtos.internal_static_com_roomreservation_collection_ListOfTimeSlots_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.roomreservation.protobuf.protos.ListOfTimeSlots.class, com.roomreservation.protobuf.protos.ListOfTimeSlots.Builder.class);
  }

  public static final int TIMESLOT_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList timeslot_;
  /**
   * <code>repeated string timeslot = 1;</code>
   * @return A list containing the timeslot.
   */
  public com.google.protobuf.ProtocolStringList
      getTimeslotList() {
    return timeslot_;
  }
  /**
   * <code>repeated string timeslot = 1;</code>
   * @return The count of timeslot.
   */
  public int getTimeslotCount() {
    return timeslot_.size();
  }
  /**
   * <code>repeated string timeslot = 1;</code>
   * @param index The index of the element to return.
   * @return The timeslot at the given index.
   */
  public java.lang.String getTimeslot(int index) {
    return timeslot_.get(index);
  }
  /**
   * <code>repeated string timeslot = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the timeslot at the given index.
   */
  public com.google.protobuf.ByteString
      getTimeslotBytes(int index) {
    return timeslot_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < timeslot_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeslot_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < timeslot_.size(); i++) {
        dataSize += computeStringSizeNoTag(timeslot_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTimeslotList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.roomreservation.protobuf.protos.ListOfTimeSlots)) {
      return super.equals(obj);
    }
    com.roomreservation.protobuf.protos.ListOfTimeSlots other = (com.roomreservation.protobuf.protos.ListOfTimeSlots) obj;

    if (!getTimeslotList()
        .equals(other.getTimeslotList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTimeslotCount() > 0) {
      hash = (37 * hash) + TIMESLOT_FIELD_NUMBER;
      hash = (53 * hash) + getTimeslotList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.ListOfTimeSlots parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.roomreservation.protobuf.protos.ListOfTimeSlots prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.roomreservation.collection.ListOfTimeSlots}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.roomreservation.collection.ListOfTimeSlots)
      com.roomreservation.protobuf.protos.ListOfTimeSlotsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roomreservation.protobuf.protos.ListOfTimeSlotsProtos.internal_static_com_roomreservation_collection_ListOfTimeSlots_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roomreservation.protobuf.protos.ListOfTimeSlotsProtos.internal_static_com_roomreservation_collection_ListOfTimeSlots_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roomreservation.protobuf.protos.ListOfTimeSlots.class, com.roomreservation.protobuf.protos.ListOfTimeSlots.Builder.class);
    }

    // Construct using com.roomreservation.protobuf.protos.ListOfTimeSlots.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timeslot_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.roomreservation.protobuf.protos.ListOfTimeSlotsProtos.internal_static_com_roomreservation_collection_ListOfTimeSlots_descriptor;
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.ListOfTimeSlots getDefaultInstanceForType() {
      return com.roomreservation.protobuf.protos.ListOfTimeSlots.getDefaultInstance();
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.ListOfTimeSlots build() {
      com.roomreservation.protobuf.protos.ListOfTimeSlots result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.ListOfTimeSlots buildPartial() {
      com.roomreservation.protobuf.protos.ListOfTimeSlots result = new com.roomreservation.protobuf.protos.ListOfTimeSlots(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        timeslot_ = timeslot_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.timeslot_ = timeslot_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.roomreservation.protobuf.protos.ListOfTimeSlots) {
        return mergeFrom((com.roomreservation.protobuf.protos.ListOfTimeSlots)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.roomreservation.protobuf.protos.ListOfTimeSlots other) {
      if (other == com.roomreservation.protobuf.protos.ListOfTimeSlots.getDefaultInstance()) return this;
      if (!other.timeslot_.isEmpty()) {
        if (timeslot_.isEmpty()) {
          timeslot_ = other.timeslot_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTimeslotIsMutable();
          timeslot_.addAll(other.timeslot_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.roomreservation.protobuf.protos.ListOfTimeSlots parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.roomreservation.protobuf.protos.ListOfTimeSlots) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList timeslot_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTimeslotIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        timeslot_ = new com.google.protobuf.LazyStringArrayList(timeslot_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @return A list containing the timeslot.
     */
    public com.google.protobuf.ProtocolStringList
        getTimeslotList() {
      return timeslot_.getUnmodifiableView();
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @return The count of timeslot.
     */
    public int getTimeslotCount() {
      return timeslot_.size();
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @param index The index of the element to return.
     * @return The timeslot at the given index.
     */
    public java.lang.String getTimeslot(int index) {
      return timeslot_.get(index);
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the timeslot at the given index.
     */
    public com.google.protobuf.ByteString
        getTimeslotBytes(int index) {
      return timeslot_.getByteString(index);
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @param index The index to set the value at.
     * @param value The timeslot to set.
     * @return This builder for chaining.
     */
    public Builder setTimeslot(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeslotIsMutable();
      timeslot_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @param value The timeslot to add.
     * @return This builder for chaining.
     */
    public Builder addTimeslot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeslotIsMutable();
      timeslot_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @param values The timeslot to add.
     * @return This builder for chaining.
     */
    public Builder addAllTimeslot(
        java.lang.Iterable<java.lang.String> values) {
      ensureTimeslotIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, timeslot_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeslot() {
      timeslot_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string timeslot = 1;</code>
     * @param value The bytes of the timeslot to add.
     * @return This builder for chaining.
     */
    public Builder addTimeslotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTimeslotIsMutable();
      timeslot_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.roomreservation.collection.ListOfTimeSlots)
  }

  // @@protoc_insertion_point(class_scope:com.roomreservation.collection.ListOfTimeSlots)
  private static final com.roomreservation.protobuf.protos.ListOfTimeSlots DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.roomreservation.protobuf.protos.ListOfTimeSlots();
  }

  public static com.roomreservation.protobuf.protos.ListOfTimeSlots getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ListOfTimeSlots>
      PARSER = new com.google.protobuf.AbstractParser<ListOfTimeSlots>() {
    @java.lang.Override
    public ListOfTimeSlots parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListOfTimeSlots(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListOfTimeSlots> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListOfTimeSlots> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.roomreservation.protobuf.protos.ListOfTimeSlots getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

