// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requestObject.proto

package com.roomreservation.protobuf.protos;

public interface RequestObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.roomreservation.collection.RequestObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string action = 1;</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>required string action = 1;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>required string action = 1;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>optional string bookingId = 2;</code>
   * @return Whether the bookingId field is set.
   */
  boolean hasBookingId();
  /**
   * <code>optional string bookingId = 2;</code>
   * @return The bookingId.
   */
  java.lang.String getBookingId();
  /**
   * <code>optional string bookingId = 2;</code>
   * @return The bytes for bookingId.
   */
  com.google.protobuf.ByteString
      getBookingIdBytes();

  /**
   * <code>optional string date = 3;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>optional string date = 3;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>optional string date = 3;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>optional string campusName = 4;</code>
   * @return Whether the campusName field is set.
   */
  boolean hasCampusName();
  /**
   * <code>optional string campusName = 4;</code>
   * @return The campusName.
   */
  java.lang.String getCampusName();
  /**
   * <code>optional string campusName = 4;</code>
   * @return The bytes for campusName.
   */
  com.google.protobuf.ByteString
      getCampusNameBytes();

  /**
   * <code>optional int32 roomNumber = 5;</code>
   * @return Whether the roomNumber field is set.
   */
  boolean hasRoomNumber();
  /**
   * <code>optional int32 roomNumber = 5;</code>
   * @return The roomNumber.
   */
  int getRoomNumber();

  /**
   * <code>optional string timeslot = 6;</code>
   * @return Whether the timeslot field is set.
   */
  boolean hasTimeslot();
  /**
   * <code>optional string timeslot = 6;</code>
   * @return The timeslot.
   */
  java.lang.String getTimeslot();
  /**
   * <code>optional string timeslot = 6;</code>
   * @return The bytes for timeslot.
   */
  com.google.protobuf.ByteString
      getTimeslotBytes();

  /**
   * <code>optional string identifier = 7;</code>
   * @return Whether the identifier field is set.
   */
  boolean hasIdentifier();
  /**
   * <code>optional string identifier = 7;</code>
   * @return The identifier.
   */
  java.lang.String getIdentifier();
  /**
   * <code>optional string identifier = 7;</code>
   * @return The bytes for identifier.
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();
}
