// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requestObject.proto

package com.roomreservation.protobuf.protos;

/**
 * Protobuf type {@code com.roomreservation.collection.RequestObject}
 */
public final class RequestObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.roomreservation.collection.RequestObject)
    RequestObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestObject.newBuilder() to construct.
  private RequestObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestObject() {
    action_ = "";
    bookingId_ = "";
    date_ = "";
    campusName_ = "";
    timeslot_ = "";
    identifier_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestObject();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            action_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            bookingId_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            date_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            campusName_ = bs;
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            roomNumber_ = input.readInt32();
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            timeslot_ = bs;
            break;
          }
          case 58: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000040;
            identifier_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.roomreservation.protobuf.protos.RequestObjectProtos.internal_static_com_roomreservation_collection_RequestObject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.roomreservation.protobuf.protos.RequestObjectProtos.internal_static_com_roomreservation_collection_RequestObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.roomreservation.protobuf.protos.RequestObject.class, com.roomreservation.protobuf.protos.RequestObject.Builder.class);
  }

  private int bitField0_;
  public static final int ACTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object action_;
  /**
   * <code>required string action = 1;</code>
   * @return Whether the action field is set.
   */
  @java.lang.Override
  public boolean hasAction() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string action = 1;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        action_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string action = 1;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOKINGID_FIELD_NUMBER = 2;
  private volatile java.lang.Object bookingId_;
  /**
   * <code>optional string bookingId = 2;</code>
   * @return Whether the bookingId field is set.
   */
  @java.lang.Override
  public boolean hasBookingId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string bookingId = 2;</code>
   * @return The bookingId.
   */
  @java.lang.Override
  public java.lang.String getBookingId() {
    java.lang.Object ref = bookingId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        bookingId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string bookingId = 2;</code>
   * @return The bytes for bookingId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBookingIdBytes() {
    java.lang.Object ref = bookingId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bookingId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object date_;
  /**
   * <code>optional string date = 3;</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string date = 3;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        date_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string date = 3;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAMPUSNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object campusName_;
  /**
   * <code>optional string campusName = 4;</code>
   * @return Whether the campusName field is set.
   */
  @java.lang.Override
  public boolean hasCampusName() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string campusName = 4;</code>
   * @return The campusName.
   */
  @java.lang.Override
  public java.lang.String getCampusName() {
    java.lang.Object ref = campusName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        campusName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string campusName = 4;</code>
   * @return The bytes for campusName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCampusNameBytes() {
    java.lang.Object ref = campusName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      campusName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMNUMBER_FIELD_NUMBER = 5;
  private int roomNumber_;
  /**
   * <code>optional int32 roomNumber = 5;</code>
   * @return Whether the roomNumber field is set.
   */
  @java.lang.Override
  public boolean hasRoomNumber() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 roomNumber = 5;</code>
   * @return The roomNumber.
   */
  @java.lang.Override
  public int getRoomNumber() {
    return roomNumber_;
  }

  public static final int TIMESLOT_FIELD_NUMBER = 6;
  private volatile java.lang.Object timeslot_;
  /**
   * <code>optional string timeslot = 6;</code>
   * @return Whether the timeslot field is set.
   */
  @java.lang.Override
  public boolean hasTimeslot() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string timeslot = 6;</code>
   * @return The timeslot.
   */
  @java.lang.Override
  public java.lang.String getTimeslot() {
    java.lang.Object ref = timeslot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        timeslot_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string timeslot = 6;</code>
   * @return The bytes for timeslot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeslotBytes() {
    java.lang.Object ref = timeslot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeslot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDENTIFIER_FIELD_NUMBER = 7;
  private volatile java.lang.Object identifier_;
  /**
   * <code>optional string identifier = 7;</code>
   * @return Whether the identifier field is set.
   */
  @java.lang.Override
  public boolean hasIdentifier() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string identifier = 7;</code>
   * @return The identifier.
   */
  @java.lang.Override
  public java.lang.String getIdentifier() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        identifier_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string identifier = 7;</code>
   * @return The bytes for identifier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdentifierBytes() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasAction()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bookingId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, date_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, campusName_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, roomNumber_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, timeslot_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, identifier_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bookingId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, date_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, campusName_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, roomNumber_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, timeslot_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, identifier_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.roomreservation.protobuf.protos.RequestObject)) {
      return super.equals(obj);
    }
    com.roomreservation.protobuf.protos.RequestObject other = (com.roomreservation.protobuf.protos.RequestObject) obj;

    if (hasAction() != other.hasAction()) return false;
    if (hasAction()) {
      if (!getAction()
          .equals(other.getAction())) return false;
    }
    if (hasBookingId() != other.hasBookingId()) return false;
    if (hasBookingId()) {
      if (!getBookingId()
          .equals(other.getBookingId())) return false;
    }
    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (hasCampusName() != other.hasCampusName()) return false;
    if (hasCampusName()) {
      if (!getCampusName()
          .equals(other.getCampusName())) return false;
    }
    if (hasRoomNumber() != other.hasRoomNumber()) return false;
    if (hasRoomNumber()) {
      if (getRoomNumber()
          != other.getRoomNumber()) return false;
    }
    if (hasTimeslot() != other.hasTimeslot()) return false;
    if (hasTimeslot()) {
      if (!getTimeslot()
          .equals(other.getTimeslot())) return false;
    }
    if (hasIdentifier() != other.hasIdentifier()) return false;
    if (hasIdentifier()) {
      if (!getIdentifier()
          .equals(other.getIdentifier())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAction()) {
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
    }
    if (hasBookingId()) {
      hash = (37 * hash) + BOOKINGID_FIELD_NUMBER;
      hash = (53 * hash) + getBookingId().hashCode();
    }
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    if (hasCampusName()) {
      hash = (37 * hash) + CAMPUSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCampusName().hashCode();
    }
    if (hasRoomNumber()) {
      hash = (37 * hash) + ROOMNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getRoomNumber();
    }
    if (hasTimeslot()) {
      hash = (37 * hash) + TIMESLOT_FIELD_NUMBER;
      hash = (53 * hash) + getTimeslot().hashCode();
    }
    if (hasIdentifier()) {
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.RequestObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.roomreservation.protobuf.protos.RequestObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.roomreservation.collection.RequestObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.roomreservation.collection.RequestObject)
      com.roomreservation.protobuf.protos.RequestObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roomreservation.protobuf.protos.RequestObjectProtos.internal_static_com_roomreservation_collection_RequestObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roomreservation.protobuf.protos.RequestObjectProtos.internal_static_com_roomreservation_collection_RequestObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roomreservation.protobuf.protos.RequestObject.class, com.roomreservation.protobuf.protos.RequestObject.Builder.class);
    }

    // Construct using com.roomreservation.protobuf.protos.RequestObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      action_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      bookingId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      date_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      campusName_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      roomNumber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      timeslot_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      identifier_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.roomreservation.protobuf.protos.RequestObjectProtos.internal_static_com_roomreservation_collection_RequestObject_descriptor;
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.RequestObject getDefaultInstanceForType() {
      return com.roomreservation.protobuf.protos.RequestObject.getDefaultInstance();
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.RequestObject build() {
      com.roomreservation.protobuf.protos.RequestObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.RequestObject buildPartial() {
      com.roomreservation.protobuf.protos.RequestObject result = new com.roomreservation.protobuf.protos.RequestObject(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.action_ = action_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.bookingId_ = bookingId_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.date_ = date_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.campusName_ = campusName_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.roomNumber_ = roomNumber_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.timeslot_ = timeslot_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.identifier_ = identifier_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.roomreservation.protobuf.protos.RequestObject) {
        return mergeFrom((com.roomreservation.protobuf.protos.RequestObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.roomreservation.protobuf.protos.RequestObject other) {
      if (other == com.roomreservation.protobuf.protos.RequestObject.getDefaultInstance()) return this;
      if (other.hasAction()) {
        bitField0_ |= 0x00000001;
        action_ = other.action_;
        onChanged();
      }
      if (other.hasBookingId()) {
        bitField0_ |= 0x00000002;
        bookingId_ = other.bookingId_;
        onChanged();
      }
      if (other.hasDate()) {
        bitField0_ |= 0x00000004;
        date_ = other.date_;
        onChanged();
      }
      if (other.hasCampusName()) {
        bitField0_ |= 0x00000008;
        campusName_ = other.campusName_;
        onChanged();
      }
      if (other.hasRoomNumber()) {
        setRoomNumber(other.getRoomNumber());
      }
      if (other.hasTimeslot()) {
        bitField0_ |= 0x00000020;
        timeslot_ = other.timeslot_;
        onChanged();
      }
      if (other.hasIdentifier()) {
        bitField0_ |= 0x00000040;
        identifier_ = other.identifier_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasAction()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.roomreservation.protobuf.protos.RequestObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.roomreservation.protobuf.protos.RequestObject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object action_ = "";
    /**
     * <code>required string action = 1;</code>
     * @return Whether the action field is set.
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string action = 1;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          action_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string action = 1;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string action = 1;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string action = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>required string action = 1;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      action_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bookingId_ = "";
    /**
     * <code>optional string bookingId = 2;</code>
     * @return Whether the bookingId field is set.
     */
    public boolean hasBookingId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string bookingId = 2;</code>
     * @return The bookingId.
     */
    public java.lang.String getBookingId() {
      java.lang.Object ref = bookingId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookingId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string bookingId = 2;</code>
     * @return The bytes for bookingId.
     */
    public com.google.protobuf.ByteString
        getBookingIdBytes() {
      java.lang.Object ref = bookingId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string bookingId = 2;</code>
     * @param value The bookingId to set.
     * @return This builder for chaining.
     */
    public Builder setBookingId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      bookingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string bookingId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookingId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bookingId_ = getDefaultInstance().getBookingId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string bookingId = 2;</code>
     * @param value The bytes for bookingId to set.
     * @return This builder for chaining.
     */
    public Builder setBookingIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      bookingId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object date_ = "";
    /**
     * <code>optional string date = 3;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string date = 3;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string date = 3;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string date = 3;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string date = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <code>optional string date = 3;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      date_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object campusName_ = "";
    /**
     * <code>optional string campusName = 4;</code>
     * @return Whether the campusName field is set.
     */
    public boolean hasCampusName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string campusName = 4;</code>
     * @return The campusName.
     */
    public java.lang.String getCampusName() {
      java.lang.Object ref = campusName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          campusName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string campusName = 4;</code>
     * @return The bytes for campusName.
     */
    public com.google.protobuf.ByteString
        getCampusNameBytes() {
      java.lang.Object ref = campusName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        campusName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string campusName = 4;</code>
     * @param value The campusName to set.
     * @return This builder for chaining.
     */
    public Builder setCampusName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      campusName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string campusName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCampusName() {
      bitField0_ = (bitField0_ & ~0x00000008);
      campusName_ = getDefaultInstance().getCampusName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string campusName = 4;</code>
     * @param value The bytes for campusName to set.
     * @return This builder for chaining.
     */
    public Builder setCampusNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      campusName_ = value;
      onChanged();
      return this;
    }

    private int roomNumber_ ;
    /**
     * <code>optional int32 roomNumber = 5;</code>
     * @return Whether the roomNumber field is set.
     */
    @java.lang.Override
    public boolean hasRoomNumber() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 roomNumber = 5;</code>
     * @return The roomNumber.
     */
    @java.lang.Override
    public int getRoomNumber() {
      return roomNumber_;
    }
    /**
     * <code>optional int32 roomNumber = 5;</code>
     * @param value The roomNumber to set.
     * @return This builder for chaining.
     */
    public Builder setRoomNumber(int value) {
      bitField0_ |= 0x00000010;
      roomNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 roomNumber = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomNumber() {
      bitField0_ = (bitField0_ & ~0x00000010);
      roomNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object timeslot_ = "";
    /**
     * <code>optional string timeslot = 6;</code>
     * @return Whether the timeslot field is set.
     */
    public boolean hasTimeslot() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string timeslot = 6;</code>
     * @return The timeslot.
     */
    public java.lang.String getTimeslot() {
      java.lang.Object ref = timeslot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeslot_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string timeslot = 6;</code>
     * @return The bytes for timeslot.
     */
    public com.google.protobuf.ByteString
        getTimeslotBytes() {
      java.lang.Object ref = timeslot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeslot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string timeslot = 6;</code>
     * @param value The timeslot to set.
     * @return This builder for chaining.
     */
    public Builder setTimeslot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      timeslot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string timeslot = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeslot() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timeslot_ = getDefaultInstance().getTimeslot();
      onChanged();
      return this;
    }
    /**
     * <code>optional string timeslot = 6;</code>
     * @param value The bytes for timeslot to set.
     * @return This builder for chaining.
     */
    public Builder setTimeslotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      timeslot_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object identifier_ = "";
    /**
     * <code>optional string identifier = 7;</code>
     * @return Whether the identifier field is set.
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string identifier = 7;</code>
     * @return The identifier.
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          identifier_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string identifier = 7;</code>
     * @return The bytes for identifier.
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string identifier = 7;</code>
     * @param value The identifier to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      identifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string identifier = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentifier() {
      bitField0_ = (bitField0_ & ~0x00000040);
      identifier_ = getDefaultInstance().getIdentifier();
      onChanged();
      return this;
    }
    /**
     * <code>optional string identifier = 7;</code>
     * @param value The bytes for identifier to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      identifier_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.roomreservation.collection.RequestObject)
  }

  // @@protoc_insertion_point(class_scope:com.roomreservation.collection.RequestObject)
  private static final com.roomreservation.protobuf.protos.RequestObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.roomreservation.protobuf.protos.RequestObject();
  }

  public static com.roomreservation.protobuf.protos.RequestObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestObject>
      PARSER = new com.google.protobuf.AbstractParser<RequestObject>() {
    @java.lang.Override
    public RequestObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestObject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestObject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.roomreservation.protobuf.protos.RequestObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

