// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responseObject.proto

package com.roomreservation.protobuf.protos;

/**
 * Protobuf type {@code com.roomreservation.collection.ResponseObject}
 */
public final class ResponseObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.roomreservation.collection.ResponseObject)
    ResponseObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseObject.newBuilder() to construct.
  private ResponseObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseObject() {
    message_ = "";
    dateTime_ = "";
    requestType_ = "";
    requestParameters_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseObject();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            message_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            dateTime_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            requestType_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            requestParameters_ = bs;
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            status_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.roomreservation.protobuf.protos.ResponseObjectProtos.internal_static_com_roomreservation_collection_ResponseObject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.roomreservation.protobuf.protos.ResponseObjectProtos.internal_static_com_roomreservation_collection_ResponseObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.roomreservation.protobuf.protos.ResponseObject.class, com.roomreservation.protobuf.protos.ResponseObject.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object message_;
  /**
   * <code>required string message = 1;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string message = 1;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATETIME_FIELD_NUMBER = 2;
  private volatile java.lang.Object dateTime_;
  /**
   * <code>required string dateTime = 2;</code>
   * @return Whether the dateTime field is set.
   */
  @java.lang.Override
  public boolean hasDateTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string dateTime = 2;</code>
   * @return The dateTime.
   */
  @java.lang.Override
  public java.lang.String getDateTime() {
    java.lang.Object ref = dateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        dateTime_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string dateTime = 2;</code>
   * @return The bytes for dateTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateTimeBytes() {
    java.lang.Object ref = dateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTTYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object requestType_;
  /**
   * <code>required string requestType = 3;</code>
   * @return Whether the requestType field is set.
   */
  @java.lang.Override
  public boolean hasRequestType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string requestType = 3;</code>
   * @return The requestType.
   */
  @java.lang.Override
  public java.lang.String getRequestType() {
    java.lang.Object ref = requestType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        requestType_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string requestType = 3;</code>
   * @return The bytes for requestType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestTypeBytes() {
    java.lang.Object ref = requestType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTPARAMETERS_FIELD_NUMBER = 4;
  private volatile java.lang.Object requestParameters_;
  /**
   * <code>required string requestParameters = 4;</code>
   * @return Whether the requestParameters field is set.
   */
  @java.lang.Override
  public boolean hasRequestParameters() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>required string requestParameters = 4;</code>
   * @return The requestParameters.
   */
  @java.lang.Override
  public java.lang.String getRequestParameters() {
    java.lang.Object ref = requestParameters_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        requestParameters_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string requestParameters = 4;</code>
   * @return The bytes for requestParameters.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestParametersBytes() {
    java.lang.Object ref = requestParameters_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestParameters_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private boolean status_;
  /**
   * <code>required bool status = 5;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>required bool status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public boolean getStatus() {
    return status_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasMessage()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDateTime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRequestType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRequestParameters()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dateTime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, requestType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, requestParameters_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBool(5, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dateTime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, requestType_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, requestParameters_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.roomreservation.protobuf.protos.ResponseObject)) {
      return super.equals(obj);
    }
    com.roomreservation.protobuf.protos.ResponseObject other = (com.roomreservation.protobuf.protos.ResponseObject) obj;

    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (hasDateTime() != other.hasDateTime()) return false;
    if (hasDateTime()) {
      if (!getDateTime()
          .equals(other.getDateTime())) return false;
    }
    if (hasRequestType() != other.hasRequestType()) return false;
    if (hasRequestType()) {
      if (!getRequestType()
          .equals(other.getRequestType())) return false;
    }
    if (hasRequestParameters() != other.hasRequestParameters()) return false;
    if (hasRequestParameters()) {
      if (!getRequestParameters()
          .equals(other.getRequestParameters())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (getStatus()
          != other.getStatus()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (hasDateTime()) {
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDateTime().hashCode();
    }
    if (hasRequestType()) {
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestType().hashCode();
    }
    if (hasRequestParameters()) {
      hash = (37 * hash) + REQUESTPARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getRequestParameters().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStatus());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.roomreservation.protobuf.protos.ResponseObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.roomreservation.protobuf.protos.ResponseObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.roomreservation.collection.ResponseObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.roomreservation.collection.ResponseObject)
      com.roomreservation.protobuf.protos.ResponseObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.roomreservation.protobuf.protos.ResponseObjectProtos.internal_static_com_roomreservation_collection_ResponseObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.roomreservation.protobuf.protos.ResponseObjectProtos.internal_static_com_roomreservation_collection_ResponseObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.roomreservation.protobuf.protos.ResponseObject.class, com.roomreservation.protobuf.protos.ResponseObject.Builder.class);
    }

    // Construct using com.roomreservation.protobuf.protos.ResponseObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      message_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      dateTime_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      requestType_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      requestParameters_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = false;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.roomreservation.protobuf.protos.ResponseObjectProtos.internal_static_com_roomreservation_collection_ResponseObject_descriptor;
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.ResponseObject getDefaultInstanceForType() {
      return com.roomreservation.protobuf.protos.ResponseObject.getDefaultInstance();
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.ResponseObject build() {
      com.roomreservation.protobuf.protos.ResponseObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.roomreservation.protobuf.protos.ResponseObject buildPartial() {
      com.roomreservation.protobuf.protos.ResponseObject result = new com.roomreservation.protobuf.protos.ResponseObject(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.message_ = message_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.dateTime_ = dateTime_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.requestType_ = requestType_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.requestParameters_ = requestParameters_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.roomreservation.protobuf.protos.ResponseObject) {
        return mergeFrom((com.roomreservation.protobuf.protos.ResponseObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.roomreservation.protobuf.protos.ResponseObject other) {
      if (other == com.roomreservation.protobuf.protos.ResponseObject.getDefaultInstance()) return this;
      if (other.hasMessage()) {
        bitField0_ |= 0x00000001;
        message_ = other.message_;
        onChanged();
      }
      if (other.hasDateTime()) {
        bitField0_ |= 0x00000002;
        dateTime_ = other.dateTime_;
        onChanged();
      }
      if (other.hasRequestType()) {
        bitField0_ |= 0x00000004;
        requestType_ = other.requestType_;
        onChanged();
      }
      if (other.hasRequestParameters()) {
        bitField0_ |= 0x00000008;
        requestParameters_ = other.requestParameters_;
        onChanged();
      }
      if (other.hasStatus()) {
        setStatus(other.getStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasMessage()) {
        return false;
      }
      if (!hasDateTime()) {
        return false;
      }
      if (!hasRequestType()) {
        return false;
      }
      if (!hasRequestParameters()) {
        return false;
      }
      if (!hasStatus()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.roomreservation.protobuf.protos.ResponseObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.roomreservation.protobuf.protos.ResponseObject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object message_ = "";
    /**
     * <code>required string message = 1;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string message = 1;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string message = 1;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string message = 1;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string message = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>required string message = 1;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateTime_ = "";
    /**
     * <code>required string dateTime = 2;</code>
     * @return Whether the dateTime field is set.
     */
    public boolean hasDateTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string dateTime = 2;</code>
     * @return The dateTime.
     */
    public java.lang.String getDateTime() {
      java.lang.Object ref = dateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dateTime_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string dateTime = 2;</code>
     * @return The bytes for dateTime.
     */
    public com.google.protobuf.ByteString
        getDateTimeBytes() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string dateTime = 2;</code>
     * @param value The dateTime to set.
     * @return This builder for chaining.
     */
    public Builder setDateTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      dateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string dateTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDateTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dateTime_ = getDefaultInstance().getDateTime();
      onChanged();
      return this;
    }
    /**
     * <code>required string dateTime = 2;</code>
     * @param value The bytes for dateTime to set.
     * @return This builder for chaining.
     */
    public Builder setDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      dateTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestType_ = "";
    /**
     * <code>required string requestType = 3;</code>
     * @return Whether the requestType field is set.
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string requestType = 3;</code>
     * @return The requestType.
     */
    public java.lang.String getRequestType() {
      java.lang.Object ref = requestType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string requestType = 3;</code>
     * @return The bytes for requestType.
     */
    public com.google.protobuf.ByteString
        getRequestTypeBytes() {
      java.lang.Object ref = requestType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string requestType = 3;</code>
     * @param value The requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      requestType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string requestType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      requestType_ = getDefaultInstance().getRequestType();
      onChanged();
      return this;
    }
    /**
     * <code>required string requestType = 3;</code>
     * @param value The bytes for requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      requestType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object requestParameters_ = "";
    /**
     * <code>required string requestParameters = 4;</code>
     * @return Whether the requestParameters field is set.
     */
    public boolean hasRequestParameters() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string requestParameters = 4;</code>
     * @return The requestParameters.
     */
    public java.lang.String getRequestParameters() {
      java.lang.Object ref = requestParameters_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestParameters_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string requestParameters = 4;</code>
     * @return The bytes for requestParameters.
     */
    public com.google.protobuf.ByteString
        getRequestParametersBytes() {
      java.lang.Object ref = requestParameters_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestParameters_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string requestParameters = 4;</code>
     * @param value The requestParameters to set.
     * @return This builder for chaining.
     */
    public Builder setRequestParameters(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      requestParameters_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string requestParameters = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestParameters() {
      bitField0_ = (bitField0_ & ~0x00000008);
      requestParameters_ = getDefaultInstance().getRequestParameters();
      onChanged();
      return this;
    }
    /**
     * <code>required string requestParameters = 4;</code>
     * @param value The bytes for requestParameters to set.
     * @return This builder for chaining.
     */
    public Builder setRequestParametersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      requestParameters_ = value;
      onChanged();
      return this;
    }

    private boolean status_ ;
    /**
     * <code>required bool status = 5;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool status = 5;</code>
     * @return The status.
     */
    @java.lang.Override
    public boolean getStatus() {
      return status_;
    }
    /**
     * <code>required bool status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(boolean value) {
      bitField0_ |= 0x00000010;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.roomreservation.collection.ResponseObject)
  }

  // @@protoc_insertion_point(class_scope:com.roomreservation.collection.ResponseObject)
  private static final com.roomreservation.protobuf.protos.ResponseObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.roomreservation.protobuf.protos.ResponseObject();
  }

  public static com.roomreservation.protobuf.protos.ResponseObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ResponseObject>
      PARSER = new com.google.protobuf.AbstractParser<ResponseObject>() {
    @java.lang.Override
    public ResponseObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseObject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseObject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.roomreservation.protobuf.protos.ResponseObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

