// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responseObject.proto

package com.roomreservation.protobuf.protos;

public final class ResponseObjectProtos {
  private ResponseObjectProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_roomreservation_collection_ResponseObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_roomreservation_collection_ResponseObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024responseObject.proto\022\036com.roomreservat" +
      "ion.collection\"s\n\016ResponseObject\022\017\n\007mess" +
      "age\030\001 \002(\t\022\020\n\010dateTime\030\002 \002(\t\022\023\n\013requestTy" +
      "pe\030\003 \002(\t\022\031\n\021requestParameters\030\004 \002(\t\022\016\n\006s" +
      "tatus\030\005 \002(\010B=\n#com.roomreservation.proto" +
      "buf.protosB\024ResponseObjectProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_roomreservation_collection_ResponseObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_roomreservation_collection_ResponseObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_roomreservation_collection_ResponseObject_descriptor,
        new java.lang.String[] { "Message", "DateTime", "RequestType", "RequestParameters", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
